### ISSUE TITLE
nested method not found

### ISSUE THREAD

**Issue by zanona** [sirbrillig/phpcs-import-detection#29]
Hi,
I have the following code where the `add_subpage` method is declared inside `admin_menu_update_sidebar`, however, whenever calling it from within that method, it seems that the plugin won't find it since it's nested. It works if I declare `add_supage` outside `admin_menu_update_sidebar` though.

```php
function admin_menu_update_sidebar() {

	function add_subpage( $title, $cat ) {
		//...
	}
	add_subpage( 'New Post', 'News' ); // < Found unimported symbol add_subpage
}
```

Is there any way to allow nested methods to work at the moment, by any chance or any suggestion as for the best way to workaround this?

Thanks in advance

**Comment by sirbrillig** [comment]
Good find! I'll have a PR up to fix that shortly.
