### ISSUE TITLE
Sniff breaks on unexpected whitespace/comments

### ISSUE THREAD

**Issue by jrfnl** [sirbrillig/phpcs-import-detection#36]
```
use Some\NS\ {
    ClassName,
    function SubLevel\functionName,
    const Constants\CONSTANT_NAME as SOME_CONSTANT,
    function SubLevel\AnotherName,
    AnotherLevel,
};
```

Will generate a `Cannot construct Symbol with no tokens` and stop the scan of the file - also for all other sniffs - as it is an uncaught exception.

Extra whitespace and comments in the middle of statements will be ignored by PHP and should be ignored by the sniff too.

**Comment by sirbrillig** [comment]
Thanks for noticing this!

**Comment by sirbrillig** [comment]
This should be fixed by https://github.com/sirbrillig/phpcs-import-detection/pull/48 for the specific instance described here, but there may be other symbol uses which allow whitespace and/or comments that are not handled. When some of those are found we can open a separate issue to handle them.

**Comment by jrfnl** [comment]
Thanks @sirbrillig!

When I have some time at some point in the future, I might take a look to see if I can find some more instances, but it may well be a while before I have the chance.
