### ISSUE TITLE
Exclude “object” from unimported symbols

### ISSUE THREAD

**Issue by djibarian** [sirbrillig/phpcs-import-detection#42]
When defining a class method in the form `function foo(object $bar): void {}` I get a `Found unimported symbol ‘object’. (ImportDetection.Imports.RequireImports.Symbol)` even with `object` being a primitive type. Is this intentional or is it because this decoration is only valid starting with PHP 7.2 and the sniff needs to be updated?

**Comment by sirbrillig** [comment]
That definitely looks like a bug to me. Thank you for reporting it!
